### ISSUE TITLE
Support scaleX

### ISSUE THREAD

**Issue by mhemesath** [vkalinichev/postcss-rtl#15]
Our team noticed that this doesn't convert the `scaleX` property. Example:
```css
.foo {
  transform: scaleX(1);
}
```

We'd expect
```css
[dir="ltr"] .foo {
  transform: scaleX(1);
}

[dir="rtl"] .foo {
  transform: scaleX(-1);
}
```

The specific use case is that we are flipping select icons with a .is-bidi flag so they change direction in RTL mode.

**Comment by vkalinichev** [comment]
I use [RTLCSS](http://rtlcss.com) for flipping properties. It doesn't flip `scaleX` by default and I think there are good reasons for this: `scaleX` is a custom case and it shouldn't be flipped in many cases.

I suggest not to rely on this plugin in this case and use an explicit declaration for it: 
```css
[dir="ltr"] .foo {
  transform: scaleX(1);
}

[dir="rtl"] .foo {
  transform: scaleX(-1);
}
```
