### ISSUE TITLE
Incorrectly generated css

### ISSUE THREAD

**Issue by johnotander** [vkalinichev/postcss-rtl#25]
Firstly, thanks for your work on this plugin!

I seem to be encountering a bit of an issue when trying to use it with a ruleset that includes `float` and `_display` properties:

##### Input

```css
.fl { float: left;  _display: inline; }
.fr { float: right; _display: inline; }
.fn { float: none; }
```

##### Output

```css
    .fl { _display: inline; }
    [dir=ltr] .fl { _float: left; }
    [dir=rtl] .fl { _float: right; }
    .fr { _display: inline; }
    [dir=ltr] .fr { _float: right; }
    [dir=rtl] .fr { _float: left; }
    [dir] .fn { float: none; }
```

Not sure what's going on yet, but I will try and at least open up a pr with a failing test case shortly.
