### ISSUE TITLE
generating [dir] prefix when ignored

### ISSUE THREAD

**Issue by adeelshahid** [vkalinichev/postcss-rtl#40]
```css
/* rtl:begin:ignore */
html, body, div, span, applet, object, iframe,
h1, h2, h3, h4, h5, h6, p, blockquote, pre,
a, abbr, acronym, address, big, cite, code,
del, dfn, em, img, ins, kbd, q, s, samp,
small, strike, strong, sub, sup, tt, var,
b, u, i, center,
dl, dt, dd, ol, ul, li,
fieldset, form, label, legend,
table, caption, tbody, tfoot, thead, tr, th, td,
article, aside, canvas, details, embed,
figure, figcaption, footer, header, hgroup,
menu, nav, output, ruby, section, summary,
time, mark, audio, video {
    margin: 0;
    padding: 0;
    border: 0;
}
/* rtl:end:ignore */
```

generates, which should not happen as we are ignoring stuff. It's only happens with margin, border, padding properties. Try this on Eric Meyer's reset.css (https://meyerweb.com/eric/tools/css/reset/)[https://meyerweb.com/eric/tools/css/reset/]

```css
[dir] html, [dir] body, [dir] div, [dir] span, [dir] applet, [dir] object, [dir] iframe,
[dir] h1, [dir] h2, [dir] h3, [dir] h4, [dir] h5, [dir] h6, [dir] p, [dir] blockquote, [dir] pre,
[dir] a, [dir] abbr, [dir] acronym, [dir] address, [dir] big, [dir] cite, [dir] code,
[dir] del, [dir] dfn, [dir] em, [dir] img, [dir] ins, [dir] kbd, [dir] q, [dir] s, [dir] samp,
[dir] small, [dir] strike, [dir] strong, [dir] sub, [dir] sup, [dir] tt, [dir] var,
[dir] b, [dir] u, [dir] i, [dir] center,
[dir] dl, [dir] dt, [dir] dd, [dir] ol, [dir] ul, [dir] li,
[dir] fieldset, [dir] form, [dir] label, [dir] legend,
[dir] table, [dir] caption, [dir] tbody, [dir] tfoot, [dir] thead, [dir] tr, [dir] th, [dir] td,
[dir] article, [dir] aside, [dir] canvas, [dir] details, [dir] embed,
[dir] figure, [dir] figcaption, [dir] footer, [dir] header, [dir] hgroup,
[dir] menu, [dir] nav, [dir] output, [dir] ruby, [dir] section, [dir] summary,
[dir] time, [dir] mark, [dir] audio, [dir] video {
	margin:0;padding:0;border:0
}
```
