### ISSUE TITLE
Feature request： Supportted  Generates RTL  or LTR only。

### ISSUE THREAD

**Issue by hiyangguo** [vkalinichev/postcss-rtl#52]
Input ：
```
.foo {
    float: right;
    text-algin:  right /* rtl:only */;
}
```

LTR output:
```
.foo {
    float: right;
}
```

RTL output:
```
.foo {
   text-algin:  right 
}
```

**Comment by vkalinichev** [comment]
@hiyangguo Sounds nice. It will be added soon. For now you can create `rtl` rule manually:
```css
.foo {
  float: right;
}
[dir=rtl] {
  text-align: right;
}
```
