### ISSUE TITLE
when use with /deep/, some styles are missing

### ISSUE THREAD

**Issue by niexias** [vkalinichev/postcss-rtl#75]
```css
<style lang="scss" scoped>
p,
h2,
h3 {
  margin: 0;
  padding: 0;
}
/deep/ .form-dialog {
  width: 720px;
  box-shadow: 2px 2px 16px rgba(166, 168, 170, 0.46);
  border-radius: 8px;
  .vi-dialog__header {
    position: relative;
    background-color: #0a1e39;
    background-image: url("~src/assets/images/new-task/form-dialog-header-bg.png");
    background-size: 100%;
    border-radius: 8px 8px 0 0;
    padding: 32px 0 24px;
  }
 ...
```
affer building, we found that the style of class “vi-dialog__header” is not existing.
